
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-lates

    steps:
      - uses: actions/checkout@2

    - name: Run a one-line script
      run: echo Hello, wold!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.